# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "Permguard CLI"
  homepage "https://community.permguard.com/"
  version "0.0.10"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/permguard/permguard/releases/download/v0.0.10/permguard_cli_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "28a60dc6bedfcd92061178ab14f7c8fb9f0892559a84b0ee2e71d81c2b1dd6e8"

      def install
        bin.install "permguard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/permguard/permguard/releases/download/v0.0.10/permguard_cli_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "66f1c93d6e58c9dcbd6dd9e154aeda8cc4fdd7779583ef04cce3bb17b8d6fe13"

      def install
        bin.install "permguard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/permguard/permguard/releases/download/v0.0.10/permguard_cli_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "e0de5a64e0d2da157a4e42ee31b0e0b86cfe1674fcabeb3d09d19771b6ceff67"
      def install
        bin.install "permguard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/permguard/permguard/releases/download/v0.0.10/permguard_cli_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "d076de957bf48d0564c89c4ec5d0c08ec7e2edb2863999e7ecdf581829da9950"
      def install
        bin.install "permguard"
      end
    end
  end

  test do
    system "#{bin}/permguard version"
  end
end
