# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "Permguard CLI"
  homepage "https://community.permguard.com/"
  version "0.0.10"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/permguard/permguard/releases/download/v0.0.10/permguard_permguard_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "0af6a398e481d2385bcf2c5f12043797e69553440e16319189ac30b39daf4cd7"

      def install
        bin.install "permguard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/permguard/permguard/releases/download/v0.0.10/permguard_permguard_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "a8b13722d09298c3af87f0abaeffc2107c50bef58380c74d2af4771870cb8be7"

      def install
        bin.install "permguard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/permguard/permguard/releases/download/v0.0.10/permguard_permguard_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "38f090ba4cc283daaf338aa56a85da3fb3685cb3fc6efcf65ce61f6a881456ca"
      def install
        bin.install "permguard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/permguard/permguard/releases/download/v0.0.10/permguard_permguard_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "c2a2e4915a8ac3afb175059608735b56416de3dc9989a4656234a365729531b8"
      def install
        bin.install "permguard"
      end
    end
  end

  test do
    system "#{bin}/permguard version"
  end
end
