# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "Permguard CLI"
  homepage "https://community.permguard.com/"
  version "0.0.11"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/permguard/permguard/releases/download/v0.0.11/permguard_cli_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "e64e41f7bd3c99bb257c54193d7431b6e25e4bca1bb9c1b900d3ce3535862042"

      def install
        bin.install "permguard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/permguard/permguard/releases/download/v0.0.11/permguard_cli_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "6b9682e89c351a91d8a6b805ad3bd7bc4c2e3e15d9796ae12aa1af6ecc333035"

      def install
        bin.install "permguard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/permguard/permguard/releases/download/v0.0.11/permguard_cli_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "e8dd4708fe569a09eef89d03496f568076e7bdb4fb649676b4e460e5a945c66e"
      def install
        bin.install "permguard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/permguard/permguard/releases/download/v0.0.11/permguard_cli_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "ce3be940966f49d91690687a957dca63b6146a7b8d0b9390b20979e975390c44"
      def install
        bin.install "permguard"
      end
    end
  end

  test do
    system "#{bin}/permguard version"
  end
end
