# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Permguard < Formula
  desc "Permguard CLI"
  homepage "https://community.permguard.com/"
  version "0.0.10"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/permguard/permguard/releases/download/v0.0.10/permguard_permguard_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "54cba7a2df4352cb69c30e5abe9cf1229be340b78c49459eeb3951b337944d57"

      def install
        bin.install "permguard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/permguard/permguard/releases/download/v0.0.10/permguard_permguard_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "7f4aadf380a2bd1bbf8d0b707a8e8ffbe2467555b953c0ce3c53198f2d5ec5b8"

      def install
        bin.install "permguard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/permguard/permguard/releases/download/v0.0.10/permguard_permguard_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "9940118859138e5409ca9be0f2229c9f33bc5863c7acc9b60b38545ea92b36b4"
      def install
        bin.install "permguard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/permguard/permguard/releases/download/v0.0.10/permguard_permguard_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "96069de15816ee611ee4c68d242086057f24ed2f97e71fde3c0058d62da94247"
      def install
        bin.install "permguard"
      end
    end
  end

  test do
    system "#{bin}/permguard version"
  end
end
