# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Permguard < Formula
  desc "Permguard CLI"
  homepage "https://community.permguard.com/"
  version "0.0.10"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/permguard/permguard/releases/download/v0.0.10/permguard_permguard_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "66db14f0b8c5a8be2ab6199e68034f6d872ff96ed1ac38e8a7f9f177c8a6554e"

      def install
        bin.install "permguard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/permguard/permguard/releases/download/v0.0.10/permguard_permguard_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "5cc349c9ffb8acec3c0ab3d6f97589bc97af692bdf1708768d814897ceb0648f"

      def install
        bin.install "permguard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/permguard/permguard/releases/download/v0.0.10/permguard_permguard_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "af1d817ac47495c87d5d8a0ee8b9fcb0498e47a31e73f9674ab0fa678b523d8f"
      def install
        bin.install "permguard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/permguard/permguard/releases/download/v0.0.10/permguard_permguard_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "47f5000694df29271996a1568c352b6ed4d91097a9740415e5b26637b465d160"
      def install
        bin.install "permguard"
      end
    end
  end

  test do
    system "#{bin}/permguard version"
  end
end
