# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli-rust@0" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "ec350e6f9f634c2db5433cef2e65e8477cd85a490248ccd47bcc4170d717419c"
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
    end
    on_intel do
      sha256 "6805553814670b3df2b4bfeb8f1e5ff16960b0103b68cf242830d5619d367a7d"
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
    end
  end

  name "cli-rust@0"
  desc "Permguard CLI (Rust)"
  homepage "https://docs.permguard.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "permguard"

  # No zap stanza required
end
