# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli-rust@0" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "a1a8c4d027451dee67229b86913aff1747625fab5d6edcc0742fe544e7f5976d"
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
    end
    on_intel do
      sha256 "8b5681fffd1546f8675b84450e51f260b4ec1bc4a0024cbd515109c9f4c033dc"
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
    end
  end

  name "cli-rust@0"
  desc "Permguard CLI (Rust)"
  homepage "https://docs.permguard.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "permguard"

  # No zap stanza required
end
