# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli" do
  name "cli"
  desc "Permguard CLI"
  homepage "https://community.permguard.com/"
  version "0.0.11"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "permguard"

  on_macos do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "aa732b7ad7fa1188b4ae6b56a91c2faa75db7550ff46a1ade7252772f00866d8"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "c3c920bcdfa0c82496c8292bdcf73b575f98ed3dccaa3b575f0cee659a4b5200"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "b9eed0dc46c8399afc558f05f1073a09c94f7e9ea9971b6441f1c3f22b4bdffe"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "7048707d16f02dc9653136d064a362a0d678bca9bbbdac223d68d8c82ac3537d"
    end
  end

  # No zap stanza required
end
