# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli" do
  name "cli"
  desc "Permguard CLI"
  homepage "https://community.permguard.com/"
  version "0.0.36"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "permguard"

  on_macos do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "6948dcd94ab9e47fd9498ca70693a6d8e73595a55d34c92ea7c037ed13c764e1"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "bbfe3dd65a00a23ee958ff1de2e12439ef5f7b875dcefad23823f0f161871443"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "f2355b6d9f7b6dcd31793ea076c6e6f4e9f526e33c4686c1b81a8f05e57a8eb5"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "da897220aaf6bc492bf7589fcc6d43c92e7fb3ebc6944389d660f1cfba3bba65"
    end
  end

  # No zap stanza required
end
