# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli" do
  name "cli"
  desc "Permguard CLI"
  homepage "https://community.permguard.com/"
  version "0.0.15"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "permguard"

  on_macos do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "4d3bc28be46d61bb6b92bbc711596b643b31c4afc72d355b16bf3a302ce2391c"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "2b8c032d300e0f8cb4b125c75860f08664464eac9ed00e719ad23cbbd253a9c7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "4e799254f554a6675605b3ca66e5accf7aba1d399b4ffa53a7abfa2b28f10383"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "5af1e0d683ef5145e26e9f8a844782ad8c951b35fcaf5ff49ed9a7360c755f23"
    end
  end

  # No zap stanza required
end
