# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli@0.0.23" do
  name "cli@0.0.23"
  desc "Permguard CLI"
  homepage "https://community.permguard.com/"
  version "0.0.23"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "permguard"

  on_macos do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "56b838878740d4a0f8958d8e0f204aa6a6a9e7886845a6caea34e9c9b342192d"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "6db6315a0f686ec4f1b869ad1caa96229f28085efe377b530258df43fc90625e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "7a14bc3baa1d1f443933ad738231e1a0878e1de50586ebcbe2f10764a33dfee9"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "4ade8ee3c08ce314ab28a566f05f6d0672532cbeab296809c9db3d3fda61c0e1"
    end
  end

  # No zap stanza required
end
