# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli@0.0.47" do
  name "cli@0.0.47"
  desc "Permguard CLI"
  homepage "https://docs.permguard.com/"
  version "0.0.47"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "permguard"

  on_macos do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "bf4085e852db0fff62d61ee0fbe5b673aba5b3d1cfe63c8750974ae6712e0466"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "f92f24bd3e0ef05f489575c890e36f3a7c9975355c497564c04bb4f6a500d538"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "c6702d5c20b5f7442d2e0339dabcc99d38e11210760a1ad33f18d383ec9f8582"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "f0be3b331e9f26ca122309af23f3c11b669f93faa5f0599cbd4a0600f2b98356"
    end
  end

  # No zap stanza required
end
