# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli@0.1.6" do
  version "0.1.6"

  on_macos do
    on_arm do
      sha256 "b1e99d1e0ef91c3e29e74cdebd5ce7c8d9f713fbbf1f79e9d0d7ffbfc1ae96d8"
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
    end
    on_intel do
      sha256 "3a9905a049a87cd9aad5d60e9197863dbabbb60387e3b7c108354838424f08c4"
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
    end
  end

  name "cli@0.1.6"
  desc "Permguard CLI"
  homepage "https://docs.permguard.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "permguard"

  # No zap stanza required
end
