# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli@0" do
  name "cli@0"
  desc "Permguard CLI"
  homepage "https://community.permguard.com/"
  version "0.0.14"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "permguard"

  on_macos do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "caeec44b47c3c8893d6605e087ceecf8ca974e542bb20cb893e5fa115bb8ddbe"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "0b892db26e5f80b526dd3d3677a11ab9f51f7c0e72fdea1138d5d27d01ab5dc9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "e4a8453c3871e9d4bc539d7838299ee8fd4836ace8aa637cf8f9c07c14a0bd9e"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "121c9b7cbabb351cc713ccb1ed5195caffa74e71a304943654bc4b103f3a44ea"
    end
  end

  # No zap stanza required
end
