# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli@0.0.49" do
  name "cli@0.0.49"
  desc "Permguard CLI"
  homepage "https://docs.permguard.com/"
  version "0.0.49"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "permguard"

  on_macos do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "b54c522ee956792c5dfdc0eca6515dfa8d2f9eb6214657b6359a5919f0f48365"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "25f329910d53b183715415f4738167f0adfd3d346242201de5e2702b6bcffe1d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "c19569eb216d2054019ea047847825a8a2686770786d53d8c98441fe2e3155e3"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "0f21363dafc1c5a7c022becff993711317ca16b3749cf0989cc23700b3a1a092"
    end
  end

  # No zap stanza required
end
