# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli@0.0.11" do
  name "cli@0.0.11"
  desc "Permguard CLI"
  homepage "https://community.permguard.com/"
  version "0.0.11"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "permguard"

  on_macos do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "e521259e2f1e5ee922197f449487bcaf44c4034e8d3cdf8680e9ac7f5f657c37"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "cb64a310783895ba13aa9acbd51049d7a1ac9baf4ecb155a5c3ad443f4e306e9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "758d79325ccc419dee9270023b1dd7460eb6ab5fe8fbee52b0c153be23583f3a"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "e8fcbe2d8ff27cbe57a2c651f72f6bd276d2f9ab4e75e7badad0ae8329d7794a"
    end
  end

  # No zap stanza required
end
