# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli@0" do
  name "cli@0"
  desc "Permguard CLI"
  homepage "https://community.permguard.com/"
  version "0.0.14"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "permguard"

  on_macos do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "1b713b0e40dfd2cbb372e33b60d1acf17dbab0ad193a69abdcdd1a7266f709b1"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "ad123fec46b19474e27cc0e031a6cefae4b21fb89cd9c13567847e7baec02819"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "3f1fc19d596e500f37b5c1899e30bc328185b42c941ba4d31147fd88d3213517"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "e0509b9f77bf1b86b7ca9411084b5ee48141b4181ff0f40c8b69744e4cae9b2f"
    end
  end

  # No zap stanza required
end
