# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli@0.0.29" do
  name "cli@0.0.29"
  desc "Permguard CLI"
  homepage "https://community.permguard.com/"
  version "0.0.29"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "permguard"

  on_macos do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "1256e2a3ebea17571db03ca50a2db73a3ead172f2166c4374908799ee758b55a"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "7e0564fc2fcce651cd51da4dda60b35f09bad8821cf035ec2dff48dd6cc8873a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "b89d4c3bfcadf98a15aeeb9c6b1627bfc2f783ecb7bed6474b37292c0e7263cd"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "d0bafdf28b2dd753266a66997d5a597a6f00937334fa7d704adbb68ed010de8a"
    end
  end

  # No zap stanza required
end
