# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli@0.0.40" do
  name "cli@0.0.40"
  desc "Permguard CLI"
  homepage "https://community.permguard.com/"
  version "0.0.40"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "permguard"

  on_macos do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "e0f50a981bf10e16e3b8e615958418d1baf36456dd51a400f5dfdd793ab18a23"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "5b2d39c1be6713279c8135b4a1e4aba6ac213c79077c33ea86023e5527cf903c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "65fd59dfa092fe70d1aca89ed2da60ae1ce76561633e63e6492cf3ec4d4a2f0b"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "e2bb38b9a6329271fa98f5e1aef41fe509cbe5679de883333a34cb5ccd785dd0"
    end
  end

  # No zap stanza required
end
