# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli@0.0.33" do
  name "cli@0.0.33"
  desc "Permguard CLI"
  homepage "https://community.permguard.com/"
  version "0.0.33"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "permguard"

  on_macos do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "c37cf4095df97df72b66c371aa79268d0e8746fbd4c2baafc1d237af458b7d63"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "00c0c29795ae3a9a8ae44185a30d4278d53436bf0d30f02bd32df2355a56ac82"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "929da263d552d06e211c200aa8b05cd86238ae087571a05e788c349eaf0033e9"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "286dd0cbf5976fd8e810ee18aeecd04bd7d2081f84c2af7146b1eb98949e8042"
    end
  end

  # No zap stanza required
end
