# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli@0.0.11" do
  name "cli@0.0.11"
  desc "Permguard CLI"
  homepage "https://community.permguard.com/"
  version "0.0.11"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "permguard"

  on_macos do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "2ab36e022251a75f21cb349c0438d3de91579b0eed056be35a6ba9f893cebe8a"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "8bce274f538fddfc7495194d368719e6e80dda73d89159865887e80d7e15be83"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "1b2f7c5f8865331575800bd969487aab811fbc407b6c7bef0e4909a2b7a22729"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "ef64ad6c35b7a73f2e27f4a9053f79d209d717f0bcf48b448fad7285516ca503"
    end
  end

  # No zap stanza required
end
