# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli@0.0.43" do
  name "cli@0.0.43"
  desc "Permguard CLI"
  homepage "https://docs.permguard.com/"
  version "0.0.43"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "permguard"

  on_macos do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "c353308d93c76faa2063a0edf8122b4261b88a12fafe3551eede59737a6df375"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "d7e6ab730796af8a1b5ce13de91e47faf465e2186cbb2bdf7c61f5d939db86b2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "eac3f69e4a3c570ac9b04aa0948846965640c98ed8b93d7219e9149cd31421d7"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "e19fa84cfc8591ef45ce55553d8d80dd6ce2452d292b567394a760b85b5791fd"
    end
  end

  # No zap stanza required
end
