# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli@0.0.21" do
  name "cli@0.0.21"
  desc "Permguard CLI"
  homepage "https://community.permguard.com/"
  version "0.0.21"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "permguard"

  on_macos do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "6a01de9fc920fb886dc6ff4872b8cae32416dbc85fc71b0f882d04a5ae14375c"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "5be779ac1e850476435d128e04da09894d9fc06bf84bdd4e79de7b357ccde803"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "546b3259c77164fe0a75463cc2af761cd4383a808eb24364b079519f83ff54b8"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "db6f651d1b2bd6db4acc34b177ff5f12edb3609d3f798420f2f161c15a00704f"
    end
  end

  # No zap stanza required
end
