# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli@0.0.31" do
  name "cli@0.0.31"
  desc "Permguard CLI"
  homepage "https://community.permguard.com/"
  version "0.0.31"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "permguard"

  on_macos do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "22c032015e217539a886ec3f9ebb8bde817c442585396c18b1966415d4af4a89"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "450751a8bc96aae9c3c366eada1c100a2af7a89c5a7aa9e8bd8e6a4311419c81"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "b910f28bdc3721853046aee56924ad15b7eff4028457c12c0aea62e260c337de"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "ca0680dca6a0ed006dc25c7fc3f6823ed436ae414a4d3ed5eea9d4b335bbf50e"
    end
  end

  # No zap stanza required
end
