# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli@0.1.5" do
  version "0.1.5"

  on_macos do
    on_arm do
      sha256 "0fdfe0586e4ceac41090bfb3f80e205b7eb4090dd1bb994788835af4a889b057"
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
    end
    on_intel do
      sha256 "0202a799c3dd0018af3287fd560df7b76e447a066961d760b0c5426af0558813"
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
    end
  end

  name "cli@0.1.5"
  desc "Permguard CLI"
  homepage "https://docs.permguard.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "permguard"

  # No zap stanza required
end
