# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli@0.0.20" do
  name "cli@0.0.20"
  desc "Permguard CLI"
  homepage "https://community.permguard.com/"
  version "0.0.20"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "permguard"

  on_macos do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "65d6af93e79b85ef2975e33d971bbcd62535155691da35327987873434832a70"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "1e6c62d1571c1f44f5a430db8a015ab416002eaa15120f9cf6c515023e92e234"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "2923ead9a67abe6bb7fade28b64b4856fa58cc8599e6e4444e21af1cf54c788a"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "fdfb4c0cb4e2c7b02de7a2a5011ffda1ab1e7f18915ca9736f86186abcce4957"
    end
  end

  # No zap stanza required
end
