# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli@0.1.3" do
  version "0.1.3"

  on_macos do
    on_arm do
      sha256 "e05c311803c204b2a54c768267968ce91aa2467b9e108940bd03cbdc1a5478df"
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
    end
    on_intel do
      sha256 "688ffa66c5e21ef30e3e6b58a2f18a8ad25e05628af30a75627c3f8aca3b21f4"
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
    end
  end

  name "cli@0.1.3"
  desc "Permguard CLI"
  homepage "https://docs.permguard.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "permguard"

  # No zap stanza required
end
