# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli@0.0.42" do
  name "cli@0.0.42"
  desc "Permguard CLI"
  homepage "https://docs.permguard.com/"
  version "0.0.42"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "permguard"

  on_macos do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "c3e93573e8fd8c10032b2c340f6905370199103a77545e031f60c24311b23f3b"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "0fa98ddc37a60e62d4e92628b456a097a7cb2ee2a62c4e895d33e102d14c4561"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "a914975cf63ef7a375f38b7495fff96c11c0d7fd2da4dea7a552d7e38fdfa3d5"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "5178ef82598ae01f081acc0540be7ffae4674fad5f579e5c624e95587b0b7d0e"
    end
  end

  # No zap stanza required
end
