# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli@0" do
  name "cli@0"
  desc "Permguard CLI"
  homepage "https://community.permguard.com/"
  version "0.0.35"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "permguard"

  on_macos do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "df5f2f9454476392e3e373d78956290343ded4e3f7b6b26dc6b682d02c540b80"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "946a5e01d35eb96e1c955c78d823cb92815f190b8783a5810472c0c3a18d5680"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "8f99dd419179c7650ebb2e6fa169acd57077328456fb99342c80e83267e045be"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "bfbf431d6caa74e2931b4524f2690a03ce3ef6e64f68f1ed8cbb4e57b4143b19"
    end
  end

  # No zap stanza required
end
