# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli@0.0.39" do
  name "cli@0.0.39"
  desc "Permguard CLI"
  homepage "https://community.permguard.com/"
  version "0.0.39"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "permguard"

  on_macos do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "c52a3b59690d17c3e86bca5587818a692c31774a17d553658c45bb28f0da251c"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "ab20ed0b8c4ea581bc7920f06799f3a6c270695dd07f1452d90a7c4eaac15e17"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "94cd9aa90fd20c597d5e0f9cd657f4a615ac1ca6eb83f141726e3e4429cd4533"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "e9e70acb8c564301a34cacdb74c0f984f08a6dd6d4a41bcc87cb599b7cf28e36"
    end
  end

  # No zap stanza required
end
