# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli@0.1.4" do
  version "0.1.4"

  on_macos do
    on_arm do
      sha256 "bd330677e7e8f26ff7e4c2e1ba7062bd83ff3e9c520ce66f4cb9d844d9c6395c"
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
    end
    on_intel do
      sha256 "245d7867d760f04555f56c5cba8e840402692bc66ac1e726627ca44c57d55477"
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
    end
  end

  name "cli@0.1.4"
  desc "Permguard CLI"
  homepage "https://docs.permguard.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "permguard"

  # No zap stanza required
end
