# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli@0.0.46" do
  name "cli@0.0.46"
  desc "Permguard CLI"
  homepage "https://docs.permguard.com/"
  version "0.0.46"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "permguard"

  on_macos do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "da6664ea4b573951b54cc56904e5488b6a9bfb4c2ec9e928f7ee7e59eae34940"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "c4ad69bac7233923028b27e12a1e459be1a8923975969ed05b0359b2fb0cc763"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "ec8ce95f081f3fcc0352da97816d6220af5ce6dff67423e35b4a7a31a3f1c062"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "bde54f7597fab991fe2cfaa49f8647e887378c6c9d8ab28b9f994aa66adb0f37"
    end
  end

  # No zap stanza required
end
