# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli@0.0.13" do
  name "cli@0.0.13"
  desc "Permguard CLI"
  homepage "https://community.permguard.com/"
  version "0.0.13"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "permguard"

  on_macos do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "d8b9a682d342aafaabf0b7be4ad588fa189f34cd7c0c88b8e7bfb490d3eac321"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "38e2535609b511ec0144cb1ba6d5f3e6fbd9c2df3900a37e6b4bfaa5c076da84"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "4b44ace710608b5276a6bb16cbbd013cd6e8b4ab1c582372536eba8b8c41e2df"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "4b480584e49e7aaf770afaf13372af0fc3ceadda1abd429f9af04119cf32d8b8"
    end
  end

  # No zap stanza required
end
