# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli@0.0.18" do
  name "cli@0.0.18"
  desc "Permguard CLI"
  homepage "https://community.permguard.com/"
  version "0.0.18"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "permguard"

  on_macos do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "970c9d2c0628fd90e792845d3f8c1b9fcfc9f81350e149672270562f6358894f"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "b14b4138c7bfdc774a82f45d1feed9e3bd6649c4c01ad2396cd8a8b526591554"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "102a330a5d2939e40ac57aea5045fb12a5577d02cad250dd84625c25cd0f75a6"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "5671cda64b242cbb3f46faef0f8e08dd623ea1b5dd030bca633d34937cd3c710"
    end
  end

  # No zap stanza required
end
