# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli@0.0.11" do
  name "cli@0.0.11"
  desc "Permguard CLI"
  homepage "https://community.permguard.com/"
  version "0.0.11"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "permguard"

  on_macos do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "f16a453bd19e12851645a4e36e7147339d3f8cc125dbf6efa937dbc8087a6c87"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "55ac44a66e9dd443011c5d124d0f738be9ec17404b3933a07f835265a0d37497"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "49522e76415858c482deb07e7c59b5776ff77d11453d9040ff288b414d299117"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "cfb2eb9d5fdec58200683af2b1dabe154928f015d6e12996175ce9f4613910b7"
    end
  end

  # No zap stanza required
end
