# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli@0.0.32" do
  name "cli@0.0.32"
  desc "Permguard CLI"
  homepage "https://community.permguard.com/"
  version "0.0.32"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "permguard"

  on_macos do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "4eacf69b34124760a32e7a1149863ecb7a6de88d1c47ba289641b01649159739"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "9a5ea6f68535e7f10debf4a168c6ef5e74abcfef9472aed46040415cbb316303"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "0b6baf785411743a8619d979c46900cee4859ef1688f1da83873eb7a4f05d281"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "4555c0b1e9edc94c711a02bf830244ae639948715d0363cc8442be770b34e93b"
    end
  end

  # No zap stanza required
end
