# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli@0.0.51" do
  name "cli@0.0.51"
  desc "Permguard CLI"
  homepage "https://docs.permguard.com/"
  version "0.0.51"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "permguard"

  on_macos do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "4bdc4cbd7d8141477d578d3c3d0cabe0713fad03826d475f27f04c411c6cbea2"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "d381657f3462f37176a99a582b272a2783278d1e32d44b2e611e343d77c81389"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "fd61b6a57ad59e0e7346f5c2a1adc704d1efc2b19cb01af1a807ee993dbb10f8"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "ec4ed967ae21e37e2c86cb9e80884b7a96598387268141e604101fecb43283e3"
    end
  end

  # No zap stanza required
end
