# This file was generated by GoReleaser. DO NOT EDIT.
cask "myproject@0" do
  name "myproject@0"
  desc "Permguard CLI"
  homepage "https://community.permguard.com/"
  version "0.0.11"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "permguard"

  on_macos do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "ff6adcb985e53ab705460ca1521ace5d8e66a66c49bebf0a7398c91058a0ba40"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Darwin_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "9058ea358240af4bae0c56473c9a8db838ef8b8a8ed70cec038d4ea7588e5afc"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_x86_64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "fbfbecb64cd0f2af67e0d6155b786dc0f2f9793c97685900f17d62ca4e5a244f"
    end
    on_arm do
      url "https://github.com/permguard/permguard/releases/download/v#{version}/permguard_cli_Linux_arm64.tar.gz",
        verified: "github.com/permguard/permguard/"
      sha256 "90d6ca7fec9b3b99162b2d92d92d15fd3ea124368a85e2804118f574621a54be"
    end
  end

  # No zap stanza required
end
